// @ts-nocheck
// Auto-generated by build.ts - do not edit
import asset0 from "../../../desktop/dist/index.html" with { type: "file" };
import asset1 from "../../../desktop/dist/assets/staplebops-01-UOWVxfVx.aac" with { type: "file" };
import asset2 from "../../../desktop/dist/assets/ibm-plex-mono-6Igp0aRH.woff2" with { type: "file" };
import asset3 from "../../../desktop/dist/assets/sprite-Fb-TFjRY.svg" with { type: "file" };
import asset4 from "../../../desktop/dist/assets/inter-FIwubZjA.woff2" with { type: "file" };
import asset5 from "../../../desktop/dist/assets/nope-03-Dr2bOnVF.aac" with { type: "file" };
import asset6 from "../../../desktop/dist/assets/index-CilGL-Qy.css" with { type: "file" };
import asset7 from "../../../desktop/dist/assets/sprite-CvkDI2I8.svg" with { type: "file" };
import asset8 from "../../../desktop/dist/assets/pierre-dark-BXuwtOqb.js" with { type: "file" };
import asset9 from "../../../desktop/dist/assets/abap-BdImnpbu.js" with { type: "file" };
import asset10 from "../../../desktop/dist/assets/pierre-light-dckrK0oj.js" with { type: "file" };
import asset11 from "../../../desktop/dist/assets/actionscript-3-CfeIJUat.js" with { type: "file" };
import asset12 from "../../../desktop/dist/assets/ada-bCR0ucgS.js" with { type: "file" };
import asset13 from "../../../desktop/dist/assets/apache-Pmp26Uib.js" with { type: "file" };
import asset14 from "../../../desktop/dist/assets/apex-DDbsPZ6N.js" with { type: "file" };
import asset15 from "../../../desktop/dist/assets/applescript-Co6uUVPk.js" with { type: "file" };
import asset16 from "../../../desktop/dist/assets/apl-dKokRX4l.js" with { type: "file" };
import asset17 from "../../../desktop/dist/assets/ara-BRHolxvo.js" with { type: "file" };
import asset18 from "../../../desktop/dist/assets/asciidoc-Dv7Oe6Be.js" with { type: "file" };
import asset19 from "../../../desktop/dist/assets/astro-CbQHKStN.js" with { type: "file" };
import asset20 from "../../../desktop/dist/assets/asm-D_Q5rh1f.js" with { type: "file" };
import asset21 from "../../../desktop/dist/assets/awk-DMzUqQB5.js" with { type: "file" };
import asset22 from "../../../desktop/dist/assets/bat-BkioyH1T.js" with { type: "file" };
import asset23 from "../../../desktop/dist/assets/beancount-k_qm7-4y.js" with { type: "file" };
import asset24 from "../../../desktop/dist/assets/berry-uYugtg8r.js" with { type: "file" };
import asset25 from "../../../desktop/dist/assets/bicep-Bmn6On1c.js" with { type: "file" };
import asset26 from "../../../desktop/dist/assets/bibtex-CHM0blh-.js" with { type: "file" };
import asset27 from "../../../desktop/dist/assets/ballerina-BFfxhgS-.js" with { type: "file" };
import asset28 from "../../../desktop/dist/assets/blade-DVc8C-J4.js" with { type: "file" };
import asset29 from "../../../desktop/dist/assets/bsl-BO_Y6i37.js" with { type: "file" };
import asset30 from "../../../desktop/dist/assets/cairo-KRGpt6FW.js" with { type: "file" };
import asset31 from "../../../desktop/dist/assets/cadence-Bv_4Rxtq.js" with { type: "file" };
import asset32 from "../../../desktop/dist/assets/clarity-D53aC0YG.js" with { type: "file" };
import asset33 from "../../../desktop/dist/assets/cobol-nwyudZeR.js" with { type: "file" };
import asset34 from "../../../desktop/dist/assets/clojure-P80f7IUj.js" with { type: "file" };
import asset35 from "../../../desktop/dist/assets/html-GMplVEZG.js" with { type: "file" };
import asset36 from "../../../desktop/dist/assets/css-DPfMkruS.js" with { type: "file" };
import asset37 from "../../../desktop/dist/assets/javascript-wDzz0qaB.js" with { type: "file" };
import asset38 from "../../../desktop/dist/assets/scss-OYdSNvt2.js" with { type: "file" };
import asset39 from "../../../desktop/dist/assets/xml-sdJ4AIDG.js" with { type: "file" };
import asset40 from "../../../desktop/dist/assets/json-Cp-IABpG.js" with { type: "file" };
import asset41 from "../../../desktop/dist/assets/java-CylS5w8V.js" with { type: "file" };
import asset42 from "../../../desktop/dist/assets/typescript-BPQ3VLAy.js" with { type: "file" };
import asset43 from "../../../desktop/dist/assets/postcss-CXtECtnM.js" with { type: "file" };
import asset44 from "../../../desktop/dist/assets/html-derivative-BFtXZ54Q.js" with { type: "file" };
import asset45 from "../../../desktop/dist/assets/tsx-COt5Ahok.js" with { type: "file" };
import asset46 from "../../../desktop/dist/assets/sql-BLtJtn59.js" with { type: "file" };
import asset47 from "../../../desktop/dist/assets/sdbl-DVxCFoDh.js" with { type: "file" };
import asset48 from "../../../desktop/dist/assets/c-BIGW1oBm.js" with { type: "file" };
import asset49 from "../../../desktop/dist/assets/python-B6aJPvgy.js" with { type: "file" };
import asset50 from "../../../desktop/dist/assets/cmake-D1j8_8rp.js" with { type: "file" };
import asset51 from "../../../desktop/dist/assets/codeql-DsOJ9woJ.js" with { type: "file" };
import asset52 from "../../../desktop/dist/assets/coffee-Ch7k5sss.js" with { type: "file" };
import asset53 from "../../../desktop/dist/assets/common-lisp-Cg-RD9OK.js" with { type: "file" };
import asset54 from "../../../desktop/dist/assets/coq-DkFqJrB1.js" with { type: "file" };
import asset55 from "../../../desktop/dist/assets/codeowners-Bp6g37R7.js" with { type: "file" };
import asset56 from "../../../desktop/dist/assets/regexp-CDVJQ6XC.js" with { type: "file" };
import asset57 from "../../../desktop/dist/assets/glsl-DplSGwfg.js" with { type: "file" };
import asset58 from "../../../desktop/dist/assets/crystal-tKQVLTB8.js" with { type: "file" };
import asset59 from "../../../desktop/dist/assets/shellscript-Yzrsuije.js" with { type: "file" };
import asset60 from "../../../desktop/dist/assets/csharp-K5feNrxe.js" with { type: "file" };
import asset61 from "../../../desktop/dist/assets/cue-D82EKSYY.js" with { type: "file" };
import asset62 from "../../../desktop/dist/assets/csv-fuZLfV_i.js" with { type: "file" };
import asset63 from "../../../desktop/dist/assets/d-85-TOEBH.js" with { type: "file" };
import asset64 from "../../../desktop/dist/assets/dart-CF10PKvl.js" with { type: "file" };
import asset65 from "../../../desktop/dist/assets/cypher-COkxafJQ.js" with { type: "file" };
import asset66 from "../../../desktop/dist/assets/dax-CEL-wOlO.js" with { type: "file" };
import asset67 from "../../../desktop/dist/assets/desktop-BmXAJ9_W.js" with { type: "file" };
import asset68 from "../../../desktop/dist/assets/diff-D97Zzqfu.js" with { type: "file" };
import asset69 from "../../../desktop/dist/assets/dream-maker-BtqSS_iP.js" with { type: "file" };
import asset70 from "../../../desktop/dist/assets/docker-BcOcwvcX.js" with { type: "file" };
import asset71 from "../../../desktop/dist/assets/edge-BkV0erSs.js" with { type: "file" };
import asset72 from "../../../desktop/dist/assets/dotenv-Da5cRb03.js" with { type: "file" };
import asset73 from "../../../desktop/dist/assets/elixir-CDX3lj18.js" with { type: "file" };
import asset74 from "../../../desktop/dist/assets/elm-DbKCFpqz.js" with { type: "file" };
import asset75 from "../../../desktop/dist/assets/emacs-lisp-C9XAeP06.js" with { type: "file" };
import asset76 from "../../../desktop/dist/assets/erb-BOJIQeun.js" with { type: "file" };
import asset77 from "../../../desktop/dist/assets/ruby-BvKwtOVI.js" with { type: "file" };
import asset78 from "../../../desktop/dist/assets/lua-BbnMAYS6.js" with { type: "file" };
import asset79 from "../../../desktop/dist/assets/yaml-Buea-lGh.js" with { type: "file" };
import asset80 from "../../../desktop/dist/assets/haml-B8DHNrY2.js" with { type: "file" };
import asset81 from "../../../desktop/dist/assets/graphql-ChdNCCLP.js" with { type: "file" };
import asset82 from "../../../desktop/dist/assets/jsx-g9-lgVsj.js" with { type: "file" };
import asset83 from "../../../desktop/dist/assets/erlang-DsQrWhSR.js" with { type: "file" };
import asset84 from "../../../desktop/dist/assets/fennel-BYunw83y.js" with { type: "file" };
import asset85 from "../../../desktop/dist/assets/fluent-C4IJs8-o.js" with { type: "file" };
import asset86 from "../../../desktop/dist/assets/fish-BvzEVeQv.js" with { type: "file" };
import asset87 from "../../../desktop/dist/assets/markdown-Cvjx9yec.js" with { type: "file" };
import asset88 from "../../../desktop/dist/assets/fortran-fixed-form-BZjJHVRy.js" with { type: "file" };
import asset89 from "../../../desktop/dist/assets/fortran-free-form-D22FLkUw.js" with { type: "file" };
import asset90 from "../../../desktop/dist/assets/fsharp-CXgrBDvD.js" with { type: "file" };
import asset91 from "../../../desktop/dist/assets/gdresource-B7Tvp0Sc.js" with { type: "file" };
import asset92 from "../../../desktop/dist/assets/gdscript-DTMYz4Jt.js" with { type: "file" };
import asset93 from "../../../desktop/dist/assets/gherkin-DyxjwDmM.js" with { type: "file" };
import asset94 from "../../../desktop/dist/assets/genie-D0YGMca9.js" with { type: "file" };
import asset95 from "../../../desktop/dist/assets/gdshader-DkwncUOv.js" with { type: "file" };
import asset96 from "../../../desktop/dist/assets/git-commit-F4YmCXRG.js" with { type: "file" };
import asset97 from "../../../desktop/dist/assets/gleam-BspZqrRM.js" with { type: "file" };
import asset98 from "../../../desktop/dist/assets/git-rebase-r7XF79zn.js" with { type: "file" };
import asset99 from "../../../desktop/dist/assets/glimmer-js-Rg0-pVw9.js" with { type: "file" };
import asset100 from "../../../desktop/dist/assets/glimmer-ts-U6CK756n.js" with { type: "file" };
import asset101 from "../../../desktop/dist/assets/groovy-gcz8RCvz.js" with { type: "file" };
import asset102 from "../../../desktop/dist/assets/gnuplot-DdkO51Og.js" with { type: "file" };
import asset103 from "../../../desktop/dist/assets/go-Dn2_MT6a.js" with { type: "file" };
import asset104 from "../../../desktop/dist/assets/hack-CaT9iCJl.js" with { type: "file" };
import asset105 from "../../../desktop/dist/assets/handlebars-BL8al0AC.js" with { type: "file" };
import asset106 from "../../../desktop/dist/assets/haskell-Df6bDoY_.js" with { type: "file" };
import asset107 from "../../../desktop/dist/assets/haxe-CzTSHFRz.js" with { type: "file" };
import asset108 from "../../../desktop/dist/assets/hjson-D5-asLiD.js" with { type: "file" };
import asset109 from "../../../desktop/dist/assets/hcl-BWvSN4gD.js" with { type: "file" };
import asset110 from "../../../desktop/dist/assets/hlsl-D3lLCCz7.js" with { type: "file" };
import asset111 from "../../../desktop/dist/assets/http-jrhK8wxY.js" with { type: "file" };
import asset112 from "../../../desktop/dist/assets/hxml-Bvhsp5Yf.js" with { type: "file" };
import asset113 from "../../../desktop/dist/assets/hurl-irOxFIW8.js" with { type: "file" };
import asset114 from "../../../desktop/dist/assets/hy-DFXneXwc.js" with { type: "file" };
import asset115 from "../../../desktop/dist/assets/imba-DGztddWO.js" with { type: "file" };
import asset116 from "../../../desktop/dist/assets/jison-wvAkD_A8.js" with { type: "file" };
import asset117 from "../../../desktop/dist/assets/ini-BEwlwnbL.js" with { type: "file" };
import asset118 from "../../../desktop/dist/assets/json5-C9tS-k6U.js" with { type: "file" };
import asset119 from "../../../desktop/dist/assets/jsonc-Des-eS-w.js" with { type: "file" };
import asset120 from "../../../desktop/dist/assets/jsonl-DcaNXYhu.js" with { type: "file" };
import asset121 from "../../../desktop/dist/assets/jsonnet-DFQXde-d.js" with { type: "file" };
import asset122 from "../../../desktop/dist/assets/jssm-C2t-YnRu.js" with { type: "file" };
import asset123 from "../../../desktop/dist/assets/julia-C8NyazO9.js" with { type: "file" };
import asset124 from "../../../desktop/dist/assets/r-DiinP2Uv.js" with { type: "file" };
import asset125 from "../../../desktop/dist/assets/kdl-DV7GczEv.js" with { type: "file" };
import asset126 from "../../../desktop/dist/assets/kotlin-BdnUsdx6.js" with { type: "file" };
import asset127 from "../../../desktop/dist/assets/kusto-BvAqAH-y.js" with { type: "file" };
import asset128 from "../../../desktop/dist/assets/latex-BdAV_C_H.js" with { type: "file" };
import asset129 from "../../../desktop/dist/assets/tex-CxkMU7Pf.js" with { type: "file" };
import asset130 from "../../../desktop/dist/assets/lean-Bc6EcWN3.js" with { type: "file" };
import asset131 from "../../../desktop/dist/assets/less-B1dDrJ26.js" with { type: "file" };
import asset132 from "../../../desktop/dist/assets/llvm-BtvRca6l.js" with { type: "file" };
import asset133 from "../../../desktop/dist/assets/liquid-DYVedYrR.js" with { type: "file" };
import asset134 from "../../../desktop/dist/assets/log-2UxHyX5q.js" with { type: "file" };
import asset135 from "../../../desktop/dist/assets/logo-BtOb2qkB.js" with { type: "file" };
import asset136 from "../../../desktop/dist/assets/make-CHLpvVh8.js" with { type: "file" };
import asset137 from "../../../desktop/dist/assets/luau-CXu1NL6O.js" with { type: "file" };
import asset138 from "../../../desktop/dist/assets/marko-CPi9NSCl.js" with { type: "file" };
import asset139 from "../../../desktop/dist/assets/matlab-D7o27uSR.js" with { type: "file" };
import asset140 from "../../../desktop/dist/assets/mdc-DUICxH0z.js" with { type: "file" };
import asset141 from "../../../desktop/dist/assets/mdx-Cmh6b_Ma.js" with { type: "file" };
import asset142 from "../../../desktop/dist/assets/mermaid-DKYwYmdq.js" with { type: "file" };
import asset143 from "../../../desktop/dist/assets/mipsasm-CKIfxQSi.js" with { type: "file" };
import asset144 from "../../../desktop/dist/assets/mojo-1DNp92w6.js" with { type: "file" };
import asset145 from "../../../desktop/dist/assets/move-Bu9oaDYs.js" with { type: "file" };
import asset146 from "../../../desktop/dist/assets/nextflow-BrzmwbiE.js" with { type: "file" };
import asset147 from "../../../desktop/dist/assets/nginx-DknmC5AR.js" with { type: "file" };
import asset148 from "../../../desktop/dist/assets/nim-CVrawwO9.js" with { type: "file" };
import asset149 from "../../../desktop/dist/assets/nushell-C-sUppwS.js" with { type: "file" };
import asset150 from "../../../desktop/dist/assets/narrat-DRg8JJMk.js" with { type: "file" };
import asset151 from "../../../desktop/dist/assets/objective-c-DXmwc3jG.js" with { type: "file" };
import asset152 from "../../../desktop/dist/assets/objective-cpp-CLxacb5B.js" with { type: "file" };
import asset153 from "../../../desktop/dist/assets/ocaml-C0hk2d4L.js" with { type: "file" };
import asset154 from "../../../desktop/dist/assets/openscad-C4EeE6gA.js" with { type: "file" };
import asset155 from "../../../desktop/dist/assets/pascal-D93ZcfNL.js" with { type: "file" };
import asset156 from "../../../desktop/dist/assets/perl-C0TMdlhV.js" with { type: "file" };
import asset157 from "../../../desktop/dist/assets/pkl-u5AG7uiY.js" with { type: "file" };
import asset158 from "../../../desktop/dist/assets/php-CDn_0X-4.js" with { type: "file" };
import asset159 from "../../../desktop/dist/assets/plsql-ChMvpjG-.js" with { type: "file" };
import asset160 from "../../../desktop/dist/assets/polar-C0HS_06l.js" with { type: "file" };
import asset161 from "../../../desktop/dist/assets/po-BTJTHyun.js" with { type: "file" };
import asset162 from "../../../desktop/dist/assets/powerquery-CEu0bR-o.js" with { type: "file" };
import asset163 from "../../../desktop/dist/assets/powershell-Dpen1YoG.js" with { type: "file" };
import asset164 from "../../../desktop/dist/assets/prolog-CbFg5uaA.js" with { type: "file" };
import asset165 from "../../../desktop/dist/assets/prisma-Dd19v3D-.js" with { type: "file" };
import asset166 from "../../../desktop/dist/assets/pug-CGlum2m_.js" with { type: "file" };
import asset167 from "../../../desktop/dist/assets/proto-DyJlTyXw.js" with { type: "file" };
import asset168 from "../../../desktop/dist/assets/puppet-BMWR74SV.js" with { type: "file" };
import asset169 from "../../../desktop/dist/assets/purescript-CklMAg4u.js" with { type: "file" };
import asset170 from "../../../desktop/dist/assets/qml-3beO22l8.js" with { type: "file" };
import asset171 from "../../../desktop/dist/assets/qmldir-C8lEn-DE.js" with { type: "file" };
import asset172 from "../../../desktop/dist/assets/qss-IeuSbFQv.js" with { type: "file" };
import asset173 from "../../../desktop/dist/assets/raku-DXvB9xmW.js" with { type: "file" };
import asset174 from "../../../desktop/dist/assets/racket-BqYA7rlc.js" with { type: "file" };
import asset175 from "../../../desktop/dist/assets/razor-CE9lU5zL.js" with { type: "file" };
import asset176 from "../../../desktop/dist/assets/reg-C-SQnVFl.js" with { type: "file" };
import asset177 from "../../../desktop/dist/assets/rel-C3B-1QV4.js" with { type: "file" };
import asset178 from "../../../desktop/dist/assets/riscv-BM1_JUlF.js" with { type: "file" };
import asset179 from "../../../desktop/dist/assets/rosmsg-BJDFO7_C.js" with { type: "file" };
import asset180 from "../../../desktop/dist/assets/sas-cz2c8ADy.js" with { type: "file" };
import asset181 from "../../../desktop/dist/assets/rst-B0xPkSld.js" with { type: "file" };
import asset182 from "../../../desktop/dist/assets/rust-B1yitclQ.js" with { type: "file" };
import asset183 from "../../../desktop/dist/assets/sass-Cj5Yp3dK.js" with { type: "file" };
import asset184 from "../../../desktop/dist/assets/scala-C151Ov-r.js" with { type: "file" };
import asset185 from "../../../desktop/dist/assets/scheme-C98Dy4si.js" with { type: "file" };
import asset186 from "../../../desktop/dist/assets/shaderlab-Dg9Lc6iA.js" with { type: "file" };
import asset187 from "../../../desktop/dist/assets/shellsession-BADoaaVG.js" with { type: "file" };
import asset188 from "../../../desktop/dist/assets/smalltalk-BERRCDM3.js" with { type: "file" };
import asset189 from "../../../desktop/dist/assets/solidity-rGO070M0.js" with { type: "file" };
import asset190 from "../../../desktop/dist/assets/soy-Brmx7dQM.js" with { type: "file" };
import asset191 from "../../../desktop/dist/assets/sparql-rVzFXLq3.js" with { type: "file" };
import asset192 from "../../../desktop/dist/assets/turtle-BsS91CYL.js" with { type: "file" };
import asset193 from "../../../desktop/dist/assets/splunk-BtCnVYZw.js" with { type: "file" };
import asset194 from "../../../desktop/dist/assets/ssh-config-_ykCGR6B.js" with { type: "file" };
import asset195 from "../../../desktop/dist/assets/stata-BH5u7GGu.js" with { type: "file" };
import asset196 from "../../../desktop/dist/assets/stylus-BEDo0Tqx.js" with { type: "file" };
import asset197 from "../../../desktop/dist/assets/svelte-3Dk4HxPD.js" with { type: "file" };
import asset198 from "../../../desktop/dist/assets/swift-Dg5xB15N.js" with { type: "file" };
import asset199 from "../../../desktop/dist/assets/system-verilog-CnnmHF94.js" with { type: "file" };
import asset200 from "../../../desktop/dist/assets/systemd-4A_iFExJ.js" with { type: "file" };
import asset201 from "../../../desktop/dist/assets/talonscript-CkByrt1z.js" with { type: "file" };
import asset202 from "../../../desktop/dist/assets/tasl-QIJgUcNo.js" with { type: "file" };
import asset203 from "../../../desktop/dist/assets/tcl-dwOrl1Do.js" with { type: "file" };
import asset204 from "../../../desktop/dist/assets/templ-W15q3VgB.js" with { type: "file" };
import asset205 from "../../../desktop/dist/assets/toml-vGWfd6FD.js" with { type: "file" };
import asset206 from "../../../desktop/dist/assets/terraform-BETggiCN.js" with { type: "file" };
import asset207 from "../../../desktop/dist/assets/twig-CO9l9SDP.js" with { type: "file" };
import asset208 from "../../../desktop/dist/assets/typespec-BGHnOYBU.js" with { type: "file" };
import asset209 from "../../../desktop/dist/assets/tsv-B_m7g4N7.js" with { type: "file" };
import asset210 from "../../../desktop/dist/assets/v-BcVCzyr7.js" with { type: "file" };
import asset211 from "../../../desktop/dist/assets/typst-DHCkPAjA.js" with { type: "file" };
import asset212 from "../../../desktop/dist/assets/vala-CsfeWuGM.js" with { type: "file" };
import asset213 from "../../../desktop/dist/assets/verilog-BQ8w6xss.js" with { type: "file" };
import asset214 from "../../../desktop/dist/assets/vb-D17OF-Vu.js" with { type: "file" };
import asset215 from "../../../desktop/dist/assets/viml-CJc9bBzg.js" with { type: "file" };
import asset216 from "../../../desktop/dist/assets/vhdl-CeAyd5Ju.js" with { type: "file" };
import asset217 from "../../../desktop/dist/assets/vue-vine-8moa0y9V.js" with { type: "file" };
import asset218 from "../../../desktop/dist/assets/vyper-CDx5xZoG.js" with { type: "file" };
import asset219 from "../../../desktop/dist/assets/vue-html-CChd_i61.js" with { type: "file" };
import asset220 from "../../../desktop/dist/assets/wenyan-BV7otONQ.js" with { type: "file" };
import asset221 from "../../../desktop/dist/assets/wasm-MzD3tlZU.js" with { type: "file" };
import asset222 from "../../../desktop/dist/assets/wikitext-BhOHFoWU.js" with { type: "file" };
import asset223 from "../../../desktop/dist/assets/wgsl-Dx-B1_4e.js" with { type: "file" };
import asset224 from "../../../desktop/dist/assets/wit-5i3qLPDT.js" with { type: "file" };
import asset225 from "../../../desktop/dist/assets/wolfram-lXgVvXCa.js" with { type: "file" };
import asset226 from "../../../desktop/dist/assets/xsl-CtQFsRM5.js" with { type: "file" };
import asset227 from "../../../desktop/dist/assets/zenscript-DVFEvuxE.js" with { type: "file" };
import asset228 from "../../../desktop/dist/assets/wasm-CG6Dc4jp.js" with { type: "file" };
import asset229 from "../../../desktop/dist/assets/zig-VOosw3JB.js" with { type: "file" };
import asset230 from "../../../desktop/dist/assets/abap-BXYWi5l2.js" with { type: "file" };
import asset231 from "../../../desktop/dist/assets/actionscript-3-LjD3sNyx.js" with { type: "file" };
import asset232 from "../../../desktop/dist/assets/ada-DeReRNhg.js" with { type: "file" };
import asset233 from "../../../desktop/dist/assets/html-DBrZJmtb.js" with { type: "file" };
import asset234 from "../../../desktop/dist/assets/javascript-XPxc2APE.js" with { type: "file" };
import asset235 from "../../../desktop/dist/assets/css-BSK200cd.js" with { type: "file" };
import asset236 from "../../../desktop/dist/assets/scss-Dk05w39G.js" with { type: "file" };
import asset237 from "../../../desktop/dist/assets/apache-CCUDgqAf.js" with { type: "file" };
import asset238 from "../../../desktop/dist/assets/apex-ynV6aGfE.js" with { type: "file" };
import asset239 from "../../../desktop/dist/assets/xml-DtyAt_xK.js" with { type: "file" };
import asset240 from "../../../desktop/dist/assets/json-CjLXzM_z.js" with { type: "file" };
import asset241 from "../../../desktop/dist/assets/apl-C-KxP0FL.js" with { type: "file" };
import asset242 from "../../../desktop/dist/assets/java-B2AjWfgk.js" with { type: "file" };
import asset243 from "../../../desktop/dist/assets/applescript-Dd26Nb5t.js" with { type: "file" };
import asset244 from "../../../desktop/dist/assets/ara-D6vCOKVX.js" with { type: "file" };
import asset245 from "../../../desktop/dist/assets/asciidoc-DZ9uQOoP.js" with { type: "file" };
import asset246 from "../../../desktop/dist/assets/astro-OEl6i-aI.js" with { type: "file" };
import asset247 from "../../../desktop/dist/assets/asm-CbVMAfFB.js" with { type: "file" };
import asset248 from "../../../desktop/dist/assets/typescript-DttGkNCf.js" with { type: "file" };
import asset249 from "../../../desktop/dist/assets/postcss-BSGhOJ4k.js" with { type: "file" };
import asset250 from "../../../desktop/dist/assets/awk-UmR4Ublb.js" with { type: "file" };
import asset251 from "../../../desktop/dist/assets/tsx-Dio8iE-N.js" with { type: "file" };
import asset252 from "../../../desktop/dist/assets/bat-Dcnh2ot_.js" with { type: "file" };
import asset253 from "../../../desktop/dist/assets/ballerina-BMbY-1wP.js" with { type: "file" };
import asset254 from "../../../desktop/dist/assets/beancount-B92nBv9q.js" with { type: "file" };
import asset255 from "../../../desktop/dist/assets/berry-C9fz7p0n.js" with { type: "file" };
import asset256 from "../../../desktop/dist/assets/bibtex-DELXwv0g.js" with { type: "file" };
import asset257 from "../../../desktop/dist/assets/blade-CwZbp2Ca.js" with { type: "file" };
import asset258 from "../../../desktop/dist/assets/bicep-D2njIRU5.js" with { type: "file" };
import asset259 from "../../../desktop/dist/assets/html-derivative-DgyNW28a.js" with { type: "file" };
import asset260 from "../../../desktop/dist/assets/bsl-C4qeDxuX.js" with { type: "file" };
import asset261 from "../../../desktop/dist/assets/c-CyUOlKFr.js" with { type: "file" };
import asset262 from "../../../desktop/dist/assets/sql-CKXjX23X.js" with { type: "file" };
import asset263 from "../../../desktop/dist/assets/sdbl-C5Q1usnU.js" with { type: "file" };
import asset264 from "../../../desktop/dist/assets/cadence-bIHbUj02.js" with { type: "file" };
import asset265 from "../../../desktop/dist/assets/cairo-C_mOTUpN.js" with { type: "file" };
import asset266 from "../../../desktop/dist/assets/python-DgE28U1V.js" with { type: "file" };
import asset267 from "../../../desktop/dist/assets/clarity-A4x-rz24.js" with { type: "file" };
import asset268 from "../../../desktop/dist/assets/clojure-Bb2-3A0I.js" with { type: "file" };
import asset269 from "../../../desktop/dist/assets/cmake-Cv5ljclQ.js" with { type: "file" };
import asset270 from "../../../desktop/dist/assets/cobol-Cg3yRVOY.js" with { type: "file" };
import asset271 from "../../../desktop/dist/assets/codeowners-CKT8dJip.js" with { type: "file" };
import asset272 from "../../../desktop/dist/assets/coffee-CSg58a7P.js" with { type: "file" };
import asset273 from "../../../desktop/dist/assets/common-lisp-v102bg8X.js" with { type: "file" };
import asset274 from "../../../desktop/dist/assets/codeql-DXd8ggn3.js" with { type: "file" };
import asset275 from "../../../desktop/dist/assets/coq-CxCehFeR.js" with { type: "file" };
import asset276 from "../../../desktop/dist/assets/regexp-BW_zLBm-.js" with { type: "file" };
import asset277 from "../../../desktop/dist/assets/glsl-Bk7TyU8J.js" with { type: "file" };
import asset278 from "../../../desktop/dist/assets/crystal-kLfOnxTY.js" with { type: "file" };
import asset279 from "../../../desktop/dist/assets/shellscript-CE-5zpiL.js" with { type: "file" };
import asset280 from "../../../desktop/dist/assets/csv-AZNL9t8Q.js" with { type: "file" };
import asset281 from "../../../desktop/dist/assets/csharp-DFQpaWb6.js" with { type: "file" };
import asset282 from "../../../desktop/dist/assets/cue-nzsbQn5T.js" with { type: "file" };
import asset283 from "../../../desktop/dist/assets/cypher-BM7Pwunj.js" with { type: "file" };
import asset284 from "../../../desktop/dist/assets/d-TG9YRPoI.js" with { type: "file" };
import asset285 from "../../../desktop/dist/assets/dart-DArdxSyj.js" with { type: "file" };
import asset286 from "../../../desktop/dist/assets/desktop-Z9LhWKWr.js" with { type: "file" };
import asset287 from "../../../desktop/dist/assets/dax-B28Cho4e.js" with { type: "file" };
import asset288 from "../../../desktop/dist/assets/docker-DIG_IqVK.js" with { type: "file" };
import asset289 from "../../../desktop/dist/assets/dotenv-Bf0GLMGc.js" with { type: "file" };
import asset290 from "../../../desktop/dist/assets/diff-BlzBhZx2.js" with { type: "file" };
import asset291 from "../../../desktop/dist/assets/dream-maker-DBhfoDN-.js" with { type: "file" };
import asset292 from "../../../desktop/dist/assets/elixir-B1OcFvXE.js" with { type: "file" };
import asset293 from "../../../desktop/dist/assets/edge-C9mkmEUa.js" with { type: "file" };
import asset294 from "../../../desktop/dist/assets/emacs-lisp-fXIB3QbG.js" with { type: "file" };
import asset295 from "../../../desktop/dist/assets/elm-BX_9EnK8.js" with { type: "file" };
import asset296 from "../../../desktop/dist/assets/erb-CjsbKF3w.js" with { type: "file" };
import asset297 from "../../../desktop/dist/assets/ruby-CHyTNJrF.js" with { type: "file" };
import asset298 from "../../../desktop/dist/assets/haml-C-C08OMF.js" with { type: "file" };
import asset299 from "../../../desktop/dist/assets/lua-tkfysgZP.js" with { type: "file" };
import asset300 from "../../../desktop/dist/assets/yaml-B92AUxDB.js" with { type: "file" };
import asset301 from "../../../desktop/dist/assets/graphql-By4-2MiP.js" with { type: "file" };
import asset302 from "../../../desktop/dist/assets/jsx-BGEKFWBk.js" with { type: "file" };
import asset303 from "../../../desktop/dist/assets/erlang-Dh270pQQ.js" with { type: "file" };
import asset304 from "../../../desktop/dist/assets/markdown-CKXSK5AY.js" with { type: "file" };
import asset305 from "../../../desktop/dist/assets/fish-BiaFC76h.js" with { type: "file" };
import asset306 from "../../../desktop/dist/assets/fennel-CKW7gc4E.js" with { type: "file" };
import asset307 from "../../../desktop/dist/assets/fluent-C1VbA1FI.js" with { type: "file" };
import asset308 from "../../../desktop/dist/assets/fortran-fixed-form-VBUom2Po.js" with { type: "file" };
import asset309 from "../../../desktop/dist/assets/fortran-free-form-xZZnushS.js" with { type: "file" };
import asset310 from "../../../desktop/dist/assets/fsharp-B6CigNpP.js" with { type: "file" };
import asset311 from "../../../desktop/dist/assets/gdresource-B57lXvxj.js" with { type: "file" };
import asset312 from "../../../desktop/dist/assets/gdshader-MbeiIFWW.js" with { type: "file" };
import asset313 from "../../../desktop/dist/assets/gdscript-etqGfJNh.js" with { type: "file" };
import asset314 from "../../../desktop/dist/assets/genie-CTXGoN_z.js" with { type: "file" };
import asset315 from "../../../desktop/dist/assets/git-commit-BicZTByO.js" with { type: "file" };
import asset316 from "../../../desktop/dist/assets/git-rebase-Bzlpfr7M.js" with { type: "file" };
import asset317 from "../../../desktop/dist/assets/gherkin-DQeIZrj7.js" with { type: "file" };
import asset318 from "../../../desktop/dist/assets/glimmer-js-cZi37nA1.js" with { type: "file" };
import asset319 from "../../../desktop/dist/assets/gleam-B-IqXlZK.js" with { type: "file" };
import asset320 from "../../../desktop/dist/assets/gnuplot-BBjkHhdK.js" with { type: "file" };
import asset321 from "../../../desktop/dist/assets/glimmer-ts-BY3QTAW9.js" with { type: "file" };
import asset322 from "../../../desktop/dist/assets/go-BYCC9JQ2.js" with { type: "file" };
import asset323 from "../../../desktop/dist/assets/groovy-DjMbfbx0.js" with { type: "file" };
import asset324 from "../../../desktop/dist/assets/hack-Ce3HFLQu.js" with { type: "file" };
import asset325 from "../../../desktop/dist/assets/handlebars-BFxKmXBZ.js" with { type: "file" };
import asset326 from "../../../desktop/dist/assets/haxe-n0Q_eay_.js" with { type: "file" };
import asset327 from "../../../desktop/dist/assets/hcl-shhv74hy.js" with { type: "file" };
import asset328 from "../../../desktop/dist/assets/haskell-DtebQ3Kv.js" with { type: "file" };
import asset329 from "../../../desktop/dist/assets/hjson-BEMFYqr7.js" with { type: "file" };
import asset330 from "../../../desktop/dist/assets/hlsl-Pefxhtaj.js" with { type: "file" };
import asset331 from "../../../desktop/dist/assets/http-D0p2QOuJ.js" with { type: "file" };
import asset332 from "../../../desktop/dist/assets/hy-CTpXmg0M.js" with { type: "file" };
import asset333 from "../../../desktop/dist/assets/hurl-CeF7EoTQ.js" with { type: "file" };
import asset334 from "../../../desktop/dist/assets/imba-z_cUhu9e.js" with { type: "file" };
import asset335 from "../../../desktop/dist/assets/ini-DOGW4-0C.js" with { type: "file" };
import asset336 from "../../../desktop/dist/assets/hxml-B_SuSTPP.js" with { type: "file" };
import asset337 from "../../../desktop/dist/assets/jison-DRGa8fbr.js" with { type: "file" };
import asset338 from "../../../desktop/dist/assets/json5-DE06a0U2.js" with { type: "file" };
import asset339 from "../../../desktop/dist/assets/jsonc-BYi4HS05.js" with { type: "file" };
import asset340 from "../../../desktop/dist/assets/jsonl-CuhIcKDk.js" with { type: "file" };
import asset341 from "../../../desktop/dist/assets/jsonnet-DtQdHwK-.js" with { type: "file" };
import asset342 from "../../../desktop/dist/assets/jssm-BlhucWo7.js" with { type: "file" };
import asset343 from "../../../desktop/dist/assets/julia-Bh5qjrIj.js" with { type: "file" };
import asset344 from "../../../desktop/dist/assets/r-BfG_C0qz.js" with { type: "file" };
import asset345 from "../../../desktop/dist/assets/kotlin-DwKqsDKK.js" with { type: "file" };
import asset346 from "../../../desktop/dist/assets/kusto-w7PrLrBe.js" with { type: "file" };
import asset347 from "../../../desktop/dist/assets/latex-BuzO6rjU.js" with { type: "file" };
import asset348 from "../../../desktop/dist/assets/kdl-DJsF4U57.js" with { type: "file" };
import asset349 from "../../../desktop/dist/assets/tex-DZ7Smwga.js" with { type: "file" };
import asset350 from "../../../desktop/dist/assets/lean-Dle5D8N4.js" with { type: "file" };
import asset351 from "../../../desktop/dist/assets/less-C76OjOdF.js" with { type: "file" };
import asset352 from "../../../desktop/dist/assets/llvm-s1WuUfOe.js" with { type: "file" };
import asset353 from "../../../desktop/dist/assets/log-CbW7hOWU.js" with { type: "file" };
import asset354 from "../../../desktop/dist/assets/liquid-DdraCjph.js" with { type: "file" };
import asset355 from "../../../desktop/dist/assets/logo-BbooMuDm.js" with { type: "file" };
import asset356 from "../../../desktop/dist/assets/luau-CBwFb-vO.js" with { type: "file" };
import asset357 from "../../../desktop/dist/assets/make-s9FKP0VE.js" with { type: "file" };
import asset358 from "../../../desktop/dist/assets/marko-BsqRlKIY.js" with { type: "file" };
import asset359 from "../../../desktop/dist/assets/matlab-BQKM-LA_.js" with { type: "file" };
import asset360 from "../../../desktop/dist/assets/mdc-BBM-UqJy.js" with { type: "file" };
import asset361 from "../../../desktop/dist/assets/mdx-BWRhHdFl.js" with { type: "file" };
import asset362 from "../../../desktop/dist/assets/mermaid-DrapLM8U.js" with { type: "file" };
import asset363 from "../../../desktop/dist/assets/mipsasm-BElnB_7Q.js" with { type: "file" };
import asset364 from "../../../desktop/dist/assets/mojo-Dz6zCmiK.js" with { type: "file" };
import asset365 from "../../../desktop/dist/assets/move-Dvu4btzz.js" with { type: "file" };
import asset366 from "../../../desktop/dist/assets/narrat-Cy2k80UN.js" with { type: "file" };
import asset367 from "../../../desktop/dist/assets/nextflow-BO4ujnzu.js" with { type: "file" };
import asset368 from "../../../desktop/dist/assets/nim-Cm6-Nayq.js" with { type: "file" };
import asset369 from "../../../desktop/dist/assets/objective-c-sgtl-PdD.js" with { type: "file" };
import asset370 from "../../../desktop/dist/assets/nushell-Dqv-0Q5X.js" with { type: "file" };
import asset371 from "../../../desktop/dist/assets/nginx-XmDIhN78.js" with { type: "file" };
import asset372 from "../../../desktop/dist/assets/objective-cpp-BTQ37cYs.js" with { type: "file" };
import asset373 from "../../../desktop/dist/assets/ocaml-BvBP9Lm0.js" with { type: "file" };
import asset374 from "../../../desktop/dist/assets/openscad-Dmi2c_42.js" with { type: "file" };
import asset375 from "../../../desktop/dist/assets/pascal-DYjw0AuS.js" with { type: "file" };
import asset376 from "../../../desktop/dist/assets/perl-Djxv1YJ9.js" with { type: "file" };
import asset377 from "../../../desktop/dist/assets/php-DEfiO3Bd.js" with { type: "file" };
import asset378 from "../../../desktop/dist/assets/pkl-Cij4Vm9z.js" with { type: "file" };
import asset379 from "../../../desktop/dist/assets/plsql-Bd6NdBJI.js" with { type: "file" };
import asset380 from "../../../desktop/dist/assets/po-CUhVi7la.js" with { type: "file" };
import asset381 from "../../../desktop/dist/assets/polar-B-qJ3AIy.js" with { type: "file" };
import asset382 from "../../../desktop/dist/assets/powerquery-CC1XieQO.js" with { type: "file" };
import asset383 from "../../../desktop/dist/assets/powershell-DdRAnR4Z.js" with { type: "file" };
import asset384 from "../../../desktop/dist/assets/prolog-bSi0SE3D.js" with { type: "file" };
import asset385 from "../../../desktop/dist/assets/prisma-C0hJlfqX.js" with { type: "file" };
import asset386 from "../../../desktop/dist/assets/proto-DIGPV07t.js" with { type: "file" };
import asset387 from "../../../desktop/dist/assets/pug-ClQUpJlV.js" with { type: "file" };
import asset388 from "../../../desktop/dist/assets/purescript-CxgsQa43.js" with { type: "file" };
import asset389 from "../../../desktop/dist/assets/puppet-ja2MI9-b.js" with { type: "file" };
import asset390 from "../../../desktop/dist/assets/qml-BEkX6VoX.js" with { type: "file" };
import asset391 from "../../../desktop/dist/assets/qmldir-DNYHzgow.js" with { type: "file" };
import asset392 from "../../../desktop/dist/assets/qss-BZsEMKxJ.js" with { type: "file" };
import asset393 from "../../../desktop/dist/assets/racket-CzHBKLyy.js" with { type: "file" };
import asset394 from "../../../desktop/dist/assets/razor-8rj0VRTp.js" with { type: "file" };
import asset395 from "../../../desktop/dist/assets/raku-CPccoUN1.js" with { type: "file" };
import asset396 from "../../../desktop/dist/assets/reg-DkqHJyC0.js" with { type: "file" };
import asset397 from "../../../desktop/dist/assets/rel-BIqKdwke.js" with { type: "file" };
import asset398 from "../../../desktop/dist/assets/rst-8IYWyo0X.js" with { type: "file" };
import asset399 from "../../../desktop/dist/assets/rosmsg-TcL_zzr8.js" with { type: "file" };
import asset400 from "../../../desktop/dist/assets/riscv-s6spwTFp.js" with { type: "file" };
import asset401 from "../../../desktop/dist/assets/rust-DJErdhjk.js" with { type: "file" };
import asset402 from "../../../desktop/dist/assets/sas-BZeeyq_z.js" with { type: "file" };
import asset403 from "../../../desktop/dist/assets/sass-CIfQ9yqV.js" with { type: "file" };
import asset404 from "../../../desktop/dist/assets/scala-CWwlNtab.js" with { type: "file" };
import asset405 from "../../../desktop/dist/assets/scheme-ByM66cy_.js" with { type: "file" };
import asset406 from "../../../desktop/dist/assets/shaderlab-DNkMdb2B.js" with { type: "file" };
import asset407 from "../../../desktop/dist/assets/shellsession-BhddCRKA.js" with { type: "file" };
import asset408 from "../../../desktop/dist/assets/smalltalk-GKfhTxrk.js" with { type: "file" };
import asset409 from "../../../desktop/dist/assets/solidity-DanOLEvk.js" with { type: "file" };
import asset410 from "../../../desktop/dist/assets/soy-C6ERzLIv.js" with { type: "file" };
import asset411 from "../../../desktop/dist/assets/sparql-CHK3vDkL.js" with { type: "file" };
import asset412 from "../../../desktop/dist/assets/turtle-whXsfw69.js" with { type: "file" };
import asset413 from "../../../desktop/dist/assets/splunk-YU1HCmJX.js" with { type: "file" };
import asset414 from "../../../desktop/dist/assets/stata-BJqnY-gO.js" with { type: "file" };
import asset415 from "../../../desktop/dist/assets/svelte-DmnhoTkn.js" with { type: "file" };
import asset416 from "../../../desktop/dist/assets/stylus-CHekGIgu.js" with { type: "file" };
import asset417 from "../../../desktop/dist/assets/ssh-config-Cpnw3KEt.js" with { type: "file" };
import asset418 from "../../../desktop/dist/assets/swift-Deru3G9w.js" with { type: "file" };
import asset419 from "../../../desktop/dist/assets/system-verilog-rKNYENrf.js" with { type: "file" };
import asset420 from "../../../desktop/dist/assets/systemd-C1FfcI00.js" with { type: "file" };
import asset421 from "../../../desktop/dist/assets/talonscript-bksoRmW6.js" with { type: "file" };
import asset422 from "../../../desktop/dist/assets/tasl-Bl4tsGRM.js" with { type: "file" };
import asset423 from "../../../desktop/dist/assets/templ-CyHhV9jl.js" with { type: "file" };
import asset424 from "../../../desktop/dist/assets/terraform-Ba94thAr.js" with { type: "file" };
import asset425 from "../../../desktop/dist/assets/toml-Btlk-g9G.js" with { type: "file" };
import asset426 from "../../../desktop/dist/assets/tsv-DYfmKMIW.js" with { type: "file" };
import asset427 from "../../../desktop/dist/assets/twig-vsFUeHgy.js" with { type: "file" };
import asset428 from "../../../desktop/dist/assets/typespec-C_z-8Pri.js" with { type: "file" };
import asset429 from "../../../desktop/dist/assets/tcl-B2_VAYrd.js" with { type: "file" };
import asset430 from "../../../desktop/dist/assets/typst-D2RORpaG.js" with { type: "file" };
import asset431 from "../../../desktop/dist/assets/v-CvM42WIw.js" with { type: "file" };
import asset432 from "../../../desktop/dist/assets/vala-B_5xOBNr.js" with { type: "file" };
import asset433 from "../../../desktop/dist/assets/vb-BVDm3zBt.js" with { type: "file" };
import asset434 from "../../../desktop/dist/assets/verilog-D5iownw6.js" with { type: "file" };
import asset435 from "../../../desktop/dist/assets/vhdl-Bmgbkl_-.js" with { type: "file" };
import asset436 from "../../../desktop/dist/assets/viml-3ZODU9FQ.js" with { type: "file" };
import asset437 from "../../../desktop/dist/assets/vue-html-CRAum25o.js" with { type: "file" };
import asset438 from "../../../desktop/dist/assets/vue-vine-CDS6dxm6.js" with { type: "file" };
import asset439 from "../../../desktop/dist/assets/vyper-B6NKdirK.js" with { type: "file" };
import asset440 from "../../../desktop/dist/assets/wasm-LUzQYg3H.js" with { type: "file" };
import asset441 from "../../../desktop/dist/assets/wenyan-8fXatRyt.js" with { type: "file" };
import asset442 from "../../../desktop/dist/assets/wgsl-CECC3vJ5.js" with { type: "file" };
import asset443 from "../../../desktop/dist/assets/wit-MEd50GYB.js" with { type: "file" };
import asset444 from "../../../desktop/dist/assets/wolfram-CmMaIVaG.js" with { type: "file" };
import asset445 from "../../../desktop/dist/assets/wikitext-BaRWL9sq.js" with { type: "file" };
import asset446 from "../../../desktop/dist/assets/xsl-Btrj9DhN.js" with { type: "file" };
import asset447 from "../../../desktop/dist/assets/zig-LhWa2ADv.js" with { type: "file" };
import asset448 from "../../../desktop/dist/assets/andromeeda-C-Jbm3Hp.js" with { type: "file" };
import asset449 from "../../../desktop/dist/assets/catppuccin-frappe-DFWUc33u.js" with { type: "file" };
import asset450 from "../../../desktop/dist/assets/ayu-dark-Cv9koXgw.js" with { type: "file" };
import asset451 from "../../../desktop/dist/assets/zenscript-Dja4fBOE.js" with { type: "file" };
import asset452 from "../../../desktop/dist/assets/catppuccin-latte-C9dUb6Cb.js" with { type: "file" };
import asset453 from "../../../desktop/dist/assets/catppuccin-macchiato-DQyhUUbL.js" with { type: "file" };
import asset454 from "../../../desktop/dist/assets/catppuccin-mocha-D87Tk5Gz.js" with { type: "file" };
import asset455 from "../../../desktop/dist/assets/dark-plus-C3mMm8J8.js" with { type: "file" };
import asset456 from "../../../desktop/dist/assets/aurora-x-D-2ljcwZ.js" with { type: "file" };
import asset457 from "../../../desktop/dist/assets/dracula-soft-BXkSAIEj.js" with { type: "file" };
import asset458 from "../../../desktop/dist/assets/everforest-dark-BgDCqdQA.js" with { type: "file" };
import asset459 from "../../../desktop/dist/assets/dracula-BzJJZx-M.js" with { type: "file" };
import asset460 from "../../../desktop/dist/assets/everforest-light-C8M2exoo.js" with { type: "file" };
import asset461 from "../../../desktop/dist/assets/github-dark-DHJKELXO.js" with { type: "file" };
import asset462 from "../../../desktop/dist/assets/github-dark-dimmed-DH5Ifo-i.js" with { type: "file" };
import asset463 from "../../../desktop/dist/assets/github-dark-high-contrast-E3gJ1_iC.js" with { type: "file" };
import asset464 from "../../../desktop/dist/assets/github-light-DAi9KRSo.js" with { type: "file" };
import asset465 from "../../../desktop/dist/assets/github-dark-default-Cuk6v7N8.js" with { type: "file" };
import asset466 from "../../../desktop/dist/assets/github-light-default-D7oLnXFd.js" with { type: "file" };
import asset467 from "../../../desktop/dist/assets/github-light-high-contrast-BfjtVDDH.js" with { type: "file" };
import asset468 from "../../../desktop/dist/assets/gruvbox-dark-hard-CFHQjOhq.js" with { type: "file" };
import asset469 from "../../../desktop/dist/assets/gruvbox-dark-medium-GsRaNv29.js" with { type: "file" };
import asset470 from "../../../desktop/dist/assets/gruvbox-dark-soft-CVdnzihN.js" with { type: "file" };
import asset471 from "../../../desktop/dist/assets/gruvbox-light-hard-CH1njM8p.js" with { type: "file" };
import asset472 from "../../../desktop/dist/assets/gruvbox-light-medium-DRw_LuNl.js" with { type: "file" };
import asset473 from "../../../desktop/dist/assets/gruvbox-light-soft-hJgmCMqR.js" with { type: "file" };
import asset474 from "../../../desktop/dist/assets/houston-DnULxvSX.js" with { type: "file" };
import asset475 from "../../../desktop/dist/assets/kanagawa-dragon-CkXjmgJE.js" with { type: "file" };
import asset476 from "../../../desktop/dist/assets/kanagawa-wave-DWedfzmr.js" with { type: "file" };
import asset477 from "../../../desktop/dist/assets/kanagawa-lotus-CfQXZHmo.js" with { type: "file" };
import asset478 from "../../../desktop/dist/assets/laserwave-DUszq2jm.js" with { type: "file" };
import asset479 from "../../../desktop/dist/assets/light-plus-B7mTdjB0.js" with { type: "file" };
import asset480 from "../../../desktop/dist/assets/material-theme-D5KoaKCx.js" with { type: "file" };
import asset481 from "../../../desktop/dist/assets/material-theme-lighter-B0m2ddpp.js" with { type: "file" };
import asset482 from "../../../desktop/dist/assets/material-theme-palenight-Csfq5Kiy.js" with { type: "file" };
import asset483 from "../../../desktop/dist/assets/material-theme-ocean-CyktbL80.js" with { type: "file" };
import asset484 from "../../../desktop/dist/assets/material-theme-darker-BfHTSMKl.js" with { type: "file" };
import asset485 from "../../../desktop/dist/assets/min-dark-CafNBF8u.js" with { type: "file" };
import asset486 from "../../../desktop/dist/assets/min-light-CTRr51gU.js" with { type: "file" };
import asset487 from "../../../desktop/dist/assets/monokai-D4h5O-jR.js" with { type: "file" };
import asset488 from "../../../desktop/dist/assets/night-owl-C39BiMTA.js" with { type: "file" };
import asset489 from "../../../desktop/dist/assets/nord-Ddv68eIx.js" with { type: "file" };
import asset490 from "../../../desktop/dist/assets/one-dark-pro-DVMEJ2y_.js" with { type: "file" };
import asset491 from "../../../desktop/dist/assets/plastic-3e1v2bzS.js" with { type: "file" };
import asset492 from "../../../desktop/dist/assets/one-light-PoHY5YXO.js" with { type: "file" };
import asset493 from "../../../desktop/dist/assets/poimandres-CS3Unz2-.js" with { type: "file" };
import asset494 from "../../../desktop/dist/assets/rose-pine-qdsjHGoJ.js" with { type: "file" };
import asset495 from "../../../desktop/dist/assets/rose-pine-dawn-DHQR4-dF.js" with { type: "file" };
import asset496 from "../../../desktop/dist/assets/red-bN70gL4F.js" with { type: "file" };
import asset497 from "../../../desktop/dist/assets/rose-pine-moon-D4_iv3hh.js" with { type: "file" };
import asset498 from "../../../desktop/dist/assets/slack-dark-BthQWCQV.js" with { type: "file" };
import asset499 from "../../../desktop/dist/assets/slack-ochin-DqwNpetd.js" with { type: "file" };
import asset500 from "../../../desktop/dist/assets/snazzy-light-Bw305WKR.js" with { type: "file" };
import asset501 from "../../../desktop/dist/assets/solarized-dark-DXbdFlpD.js" with { type: "file" };
import asset502 from "../../../desktop/dist/assets/synthwave-84-CbfX1IO0.js" with { type: "file" };
import asset503 from "../../../desktop/dist/assets/solarized-light-L9t79GZl.js" with { type: "file" };
import asset504 from "../../../desktop/dist/assets/tokyo-night-hegEt444.js" with { type: "file" };
import asset505 from "../../../desktop/dist/assets/vitesse-black-Bkuqu6BP.js" with { type: "file" };
import asset506 from "../../../desktop/dist/assets/vitesse-dark-D0r3Knsf.js" with { type: "file" };
import asset507 from "../../../desktop/dist/assets/vitesse-light-CVO1_9PV.js" with { type: "file" };
import asset508 from "../../../desktop/dist/assets/cpp-CofmeUqb.js" with { type: "file" };
import asset509 from "../../../desktop/dist/assets/jinja-4LBKfQ-Z.js" with { type: "file" };
import asset510 from "../../../desktop/dist/assets/vesper-DU1UobuO.js" with { type: "file" };
import asset511 from "../../../desktop/dist/assets/nix-c8nO5XWb.js" with { type: "file" };
import asset512 from "../../../desktop/dist/assets/cpp-C28rag7_.js" with { type: "file" };
import asset513 from "../../../desktop/dist/assets/jinja-DlBE7Xgz.js" with { type: "file" };
import asset514 from "../../../desktop/dist/assets/nix-DcZRBjkC.js" with { type: "file" };
import asset515 from "../../../desktop/dist/assets/angular-ts-BwZT4LLn.js" with { type: "file" };
import asset516 from "../../../desktop/dist/assets/angular-ts-BfBSdvnY.js" with { type: "file" };
import asset517 from "../../../desktop/dist/assets/vue-DnHKYNfI.js" with { type: "file" };
import asset518 from "../../../desktop/dist/assets/angular-html-CU67Zn6k.js" with { type: "file" };
import asset519 from "../../../desktop/dist/assets/angular-html-6NEUuZou.js" with { type: "file" };
import asset520 from "../../../desktop/dist/assets/vue-BJuclMoA.js" with { type: "file" };
import asset521 from "../../../desktop/dist/assets/ts-tags-zn1MmPIZ.js" with { type: "file" };
import asset522 from "../../../desktop/dist/assets/index-DvAfiR5P.js" with { type: "file" };
import asset523 from "../../../desktop/dist/assets/worker-NULm4lOi.js" with { type: "file" };
import asset524 from "../../../desktop/dist/assets/ts-tags-DMPjx__B.js" with { type: "file" };

export const desktopAssets: Record<string, string> = {
  "/": asset0,
  "/assets/staplebops-01-UOWVxfVx.aac": asset1,
  "/assets/ibm-plex-mono-6Igp0aRH.woff2": asset2,
  "/assets/sprite-Fb-TFjRY.svg": asset3,
  "/assets/inter-FIwubZjA.woff2": asset4,
  "/assets/nope-03-Dr2bOnVF.aac": asset5,
  "/assets/index-CilGL-Qy.css": asset6,
  "/assets/sprite-CvkDI2I8.svg": asset7,
  "/assets/pierre-dark-BXuwtOqb.js": asset8,
  "/assets/abap-BdImnpbu.js": asset9,
  "/assets/pierre-light-dckrK0oj.js": asset10,
  "/assets/actionscript-3-CfeIJUat.js": asset11,
  "/assets/ada-bCR0ucgS.js": asset12,
  "/assets/apache-Pmp26Uib.js": asset13,
  "/assets/apex-DDbsPZ6N.js": asset14,
  "/assets/applescript-Co6uUVPk.js": asset15,
  "/assets/apl-dKokRX4l.js": asset16,
  "/assets/ara-BRHolxvo.js": asset17,
  "/assets/asciidoc-Dv7Oe6Be.js": asset18,
  "/assets/astro-CbQHKStN.js": asset19,
  "/assets/asm-D_Q5rh1f.js": asset20,
  "/assets/awk-DMzUqQB5.js": asset21,
  "/assets/bat-BkioyH1T.js": asset22,
  "/assets/beancount-k_qm7-4y.js": asset23,
  "/assets/berry-uYugtg8r.js": asset24,
  "/assets/bicep-Bmn6On1c.js": asset25,
  "/assets/bibtex-CHM0blh-.js": asset26,
  "/assets/ballerina-BFfxhgS-.js": asset27,
  "/assets/blade-DVc8C-J4.js": asset28,
  "/assets/bsl-BO_Y6i37.js": asset29,
  "/assets/cairo-KRGpt6FW.js": asset30,
  "/assets/cadence-Bv_4Rxtq.js": asset31,
  "/assets/clarity-D53aC0YG.js": asset32,
  "/assets/cobol-nwyudZeR.js": asset33,
  "/assets/clojure-P80f7IUj.js": asset34,
  "/assets/html-GMplVEZG.js": asset35,
  "/assets/css-DPfMkruS.js": asset36,
  "/assets/javascript-wDzz0qaB.js": asset37,
  "/assets/scss-OYdSNvt2.js": asset38,
  "/assets/xml-sdJ4AIDG.js": asset39,
  "/assets/json-Cp-IABpG.js": asset40,
  "/assets/java-CylS5w8V.js": asset41,
  "/assets/typescript-BPQ3VLAy.js": asset42,
  "/assets/postcss-CXtECtnM.js": asset43,
  "/assets/html-derivative-BFtXZ54Q.js": asset44,
  "/assets/tsx-COt5Ahok.js": asset45,
  "/assets/sql-BLtJtn59.js": asset46,
  "/assets/sdbl-DVxCFoDh.js": asset47,
  "/assets/c-BIGW1oBm.js": asset48,
  "/assets/python-B6aJPvgy.js": asset49,
  "/assets/cmake-D1j8_8rp.js": asset50,
  "/assets/codeql-DsOJ9woJ.js": asset51,
  "/assets/coffee-Ch7k5sss.js": asset52,
  "/assets/common-lisp-Cg-RD9OK.js": asset53,
  "/assets/coq-DkFqJrB1.js": asset54,
  "/assets/codeowners-Bp6g37R7.js": asset55,
  "/assets/regexp-CDVJQ6XC.js": asset56,
  "/assets/glsl-DplSGwfg.js": asset57,
  "/assets/crystal-tKQVLTB8.js": asset58,
  "/assets/shellscript-Yzrsuije.js": asset59,
  "/assets/csharp-K5feNrxe.js": asset60,
  "/assets/cue-D82EKSYY.js": asset61,
  "/assets/csv-fuZLfV_i.js": asset62,
  "/assets/d-85-TOEBH.js": asset63,
  "/assets/dart-CF10PKvl.js": asset64,
  "/assets/cypher-COkxafJQ.js": asset65,
  "/assets/dax-CEL-wOlO.js": asset66,
  "/assets/desktop-BmXAJ9_W.js": asset67,
  "/assets/diff-D97Zzqfu.js": asset68,
  "/assets/dream-maker-BtqSS_iP.js": asset69,
  "/assets/docker-BcOcwvcX.js": asset70,
  "/assets/edge-BkV0erSs.js": asset71,
  "/assets/dotenv-Da5cRb03.js": asset72,
  "/assets/elixir-CDX3lj18.js": asset73,
  "/assets/elm-DbKCFpqz.js": asset74,
  "/assets/emacs-lisp-C9XAeP06.js": asset75,
  "/assets/erb-BOJIQeun.js": asset76,
  "/assets/ruby-BvKwtOVI.js": asset77,
  "/assets/lua-BbnMAYS6.js": asset78,
  "/assets/yaml-Buea-lGh.js": asset79,
  "/assets/haml-B8DHNrY2.js": asset80,
  "/assets/graphql-ChdNCCLP.js": asset81,
  "/assets/jsx-g9-lgVsj.js": asset82,
  "/assets/erlang-DsQrWhSR.js": asset83,
  "/assets/fennel-BYunw83y.js": asset84,
  "/assets/fluent-C4IJs8-o.js": asset85,
  "/assets/fish-BvzEVeQv.js": asset86,
  "/assets/markdown-Cvjx9yec.js": asset87,
  "/assets/fortran-fixed-form-BZjJHVRy.js": asset88,
  "/assets/fortran-free-form-D22FLkUw.js": asset89,
  "/assets/fsharp-CXgrBDvD.js": asset90,
  "/assets/gdresource-B7Tvp0Sc.js": asset91,
  "/assets/gdscript-DTMYz4Jt.js": asset92,
  "/assets/gherkin-DyxjwDmM.js": asset93,
  "/assets/genie-D0YGMca9.js": asset94,
  "/assets/gdshader-DkwncUOv.js": asset95,
  "/assets/git-commit-F4YmCXRG.js": asset96,
  "/assets/gleam-BspZqrRM.js": asset97,
  "/assets/git-rebase-r7XF79zn.js": asset98,
  "/assets/glimmer-js-Rg0-pVw9.js": asset99,
  "/assets/glimmer-ts-U6CK756n.js": asset100,
  "/assets/groovy-gcz8RCvz.js": asset101,
  "/assets/gnuplot-DdkO51Og.js": asset102,
  "/assets/go-Dn2_MT6a.js": asset103,
  "/assets/hack-CaT9iCJl.js": asset104,
  "/assets/handlebars-BL8al0AC.js": asset105,
  "/assets/haskell-Df6bDoY_.js": asset106,
  "/assets/haxe-CzTSHFRz.js": asset107,
  "/assets/hjson-D5-asLiD.js": asset108,
  "/assets/hcl-BWvSN4gD.js": asset109,
  "/assets/hlsl-D3lLCCz7.js": asset110,
  "/assets/http-jrhK8wxY.js": asset111,
  "/assets/hxml-Bvhsp5Yf.js": asset112,
  "/assets/hurl-irOxFIW8.js": asset113,
  "/assets/hy-DFXneXwc.js": asset114,
  "/assets/imba-DGztddWO.js": asset115,
  "/assets/jison-wvAkD_A8.js": asset116,
  "/assets/ini-BEwlwnbL.js": asset117,
  "/assets/json5-C9tS-k6U.js": asset118,
  "/assets/jsonc-Des-eS-w.js": asset119,
  "/assets/jsonl-DcaNXYhu.js": asset120,
  "/assets/jsonnet-DFQXde-d.js": asset121,
  "/assets/jssm-C2t-YnRu.js": asset122,
  "/assets/julia-C8NyazO9.js": asset123,
  "/assets/r-DiinP2Uv.js": asset124,
  "/assets/kdl-DV7GczEv.js": asset125,
  "/assets/kotlin-BdnUsdx6.js": asset126,
  "/assets/kusto-BvAqAH-y.js": asset127,
  "/assets/latex-BdAV_C_H.js": asset128,
  "/assets/tex-CxkMU7Pf.js": asset129,
  "/assets/lean-Bc6EcWN3.js": asset130,
  "/assets/less-B1dDrJ26.js": asset131,
  "/assets/llvm-BtvRca6l.js": asset132,
  "/assets/liquid-DYVedYrR.js": asset133,
  "/assets/log-2UxHyX5q.js": asset134,
  "/assets/logo-BtOb2qkB.js": asset135,
  "/assets/make-CHLpvVh8.js": asset136,
  "/assets/luau-CXu1NL6O.js": asset137,
  "/assets/marko-CPi9NSCl.js": asset138,
  "/assets/matlab-D7o27uSR.js": asset139,
  "/assets/mdc-DUICxH0z.js": asset140,
  "/assets/mdx-Cmh6b_Ma.js": asset141,
  "/assets/mermaid-DKYwYmdq.js": asset142,
  "/assets/mipsasm-CKIfxQSi.js": asset143,
  "/assets/mojo-1DNp92w6.js": asset144,
  "/assets/move-Bu9oaDYs.js": asset145,
  "/assets/nextflow-BrzmwbiE.js": asset146,
  "/assets/nginx-DknmC5AR.js": asset147,
  "/assets/nim-CVrawwO9.js": asset148,
  "/assets/nushell-C-sUppwS.js": asset149,
  "/assets/narrat-DRg8JJMk.js": asset150,
  "/assets/objective-c-DXmwc3jG.js": asset151,
  "/assets/objective-cpp-CLxacb5B.js": asset152,
  "/assets/ocaml-C0hk2d4L.js": asset153,
  "/assets/openscad-C4EeE6gA.js": asset154,
  "/assets/pascal-D93ZcfNL.js": asset155,
  "/assets/perl-C0TMdlhV.js": asset156,
  "/assets/pkl-u5AG7uiY.js": asset157,
  "/assets/php-CDn_0X-4.js": asset158,
  "/assets/plsql-ChMvpjG-.js": asset159,
  "/assets/polar-C0HS_06l.js": asset160,
  "/assets/po-BTJTHyun.js": asset161,
  "/assets/powerquery-CEu0bR-o.js": asset162,
  "/assets/powershell-Dpen1YoG.js": asset163,
  "/assets/prolog-CbFg5uaA.js": asset164,
  "/assets/prisma-Dd19v3D-.js": asset165,
  "/assets/pug-CGlum2m_.js": asset166,
  "/assets/proto-DyJlTyXw.js": asset167,
  "/assets/puppet-BMWR74SV.js": asset168,
  "/assets/purescript-CklMAg4u.js": asset169,
  "/assets/qml-3beO22l8.js": asset170,
  "/assets/qmldir-C8lEn-DE.js": asset171,
  "/assets/qss-IeuSbFQv.js": asset172,
  "/assets/raku-DXvB9xmW.js": asset173,
  "/assets/racket-BqYA7rlc.js": asset174,
  "/assets/razor-CE9lU5zL.js": asset175,
  "/assets/reg-C-SQnVFl.js": asset176,
  "/assets/rel-C3B-1QV4.js": asset177,
  "/assets/riscv-BM1_JUlF.js": asset178,
  "/assets/rosmsg-BJDFO7_C.js": asset179,
  "/assets/sas-cz2c8ADy.js": asset180,
  "/assets/rst-B0xPkSld.js": asset181,
  "/assets/rust-B1yitclQ.js": asset182,
  "/assets/sass-Cj5Yp3dK.js": asset183,
  "/assets/scala-C151Ov-r.js": asset184,
  "/assets/scheme-C98Dy4si.js": asset185,
  "/assets/shaderlab-Dg9Lc6iA.js": asset186,
  "/assets/shellsession-BADoaaVG.js": asset187,
  "/assets/smalltalk-BERRCDM3.js": asset188,
  "/assets/solidity-rGO070M0.js": asset189,
  "/assets/soy-Brmx7dQM.js": asset190,
  "/assets/sparql-rVzFXLq3.js": asset191,
  "/assets/turtle-BsS91CYL.js": asset192,
  "/assets/splunk-BtCnVYZw.js": asset193,
  "/assets/ssh-config-_ykCGR6B.js": asset194,
  "/assets/stata-BH5u7GGu.js": asset195,
  "/assets/stylus-BEDo0Tqx.js": asset196,
  "/assets/svelte-3Dk4HxPD.js": asset197,
  "/assets/swift-Dg5xB15N.js": asset198,
  "/assets/system-verilog-CnnmHF94.js": asset199,
  "/assets/systemd-4A_iFExJ.js": asset200,
  "/assets/talonscript-CkByrt1z.js": asset201,
  "/assets/tasl-QIJgUcNo.js": asset202,
  "/assets/tcl-dwOrl1Do.js": asset203,
  "/assets/templ-W15q3VgB.js": asset204,
  "/assets/toml-vGWfd6FD.js": asset205,
  "/assets/terraform-BETggiCN.js": asset206,
  "/assets/twig-CO9l9SDP.js": asset207,
  "/assets/typespec-BGHnOYBU.js": asset208,
  "/assets/tsv-B_m7g4N7.js": asset209,
  "/assets/v-BcVCzyr7.js": asset210,
  "/assets/typst-DHCkPAjA.js": asset211,
  "/assets/vala-CsfeWuGM.js": asset212,
  "/assets/verilog-BQ8w6xss.js": asset213,
  "/assets/vb-D17OF-Vu.js": asset214,
  "/assets/viml-CJc9bBzg.js": asset215,
  "/assets/vhdl-CeAyd5Ju.js": asset216,
  "/assets/vue-vine-8moa0y9V.js": asset217,
  "/assets/vyper-CDx5xZoG.js": asset218,
  "/assets/vue-html-CChd_i61.js": asset219,
  "/assets/wenyan-BV7otONQ.js": asset220,
  "/assets/wasm-MzD3tlZU.js": asset221,
  "/assets/wikitext-BhOHFoWU.js": asset222,
  "/assets/wgsl-Dx-B1_4e.js": asset223,
  "/assets/wit-5i3qLPDT.js": asset224,
  "/assets/wolfram-lXgVvXCa.js": asset225,
  "/assets/xsl-CtQFsRM5.js": asset226,
  "/assets/zenscript-DVFEvuxE.js": asset227,
  "/assets/wasm-CG6Dc4jp.js": asset228,
  "/assets/zig-VOosw3JB.js": asset229,
  "/assets/abap-BXYWi5l2.js": asset230,
  "/assets/actionscript-3-LjD3sNyx.js": asset231,
  "/assets/ada-DeReRNhg.js": asset232,
  "/assets/html-DBrZJmtb.js": asset233,
  "/assets/javascript-XPxc2APE.js": asset234,
  "/assets/css-BSK200cd.js": asset235,
  "/assets/scss-Dk05w39G.js": asset236,
  "/assets/apache-CCUDgqAf.js": asset237,
  "/assets/apex-ynV6aGfE.js": asset238,
  "/assets/xml-DtyAt_xK.js": asset239,
  "/assets/json-CjLXzM_z.js": asset240,
  "/assets/apl-C-KxP0FL.js": asset241,
  "/assets/java-B2AjWfgk.js": asset242,
  "/assets/applescript-Dd26Nb5t.js": asset243,
  "/assets/ara-D6vCOKVX.js": asset244,
  "/assets/asciidoc-DZ9uQOoP.js": asset245,
  "/assets/astro-OEl6i-aI.js": asset246,
  "/assets/asm-CbVMAfFB.js": asset247,
  "/assets/typescript-DttGkNCf.js": asset248,
  "/assets/postcss-BSGhOJ4k.js": asset249,
  "/assets/awk-UmR4Ublb.js": asset250,
  "/assets/tsx-Dio8iE-N.js": asset251,
  "/assets/bat-Dcnh2ot_.js": asset252,
  "/assets/ballerina-BMbY-1wP.js": asset253,
  "/assets/beancount-B92nBv9q.js": asset254,
  "/assets/berry-C9fz7p0n.js": asset255,
  "/assets/bibtex-DELXwv0g.js": asset256,
  "/assets/blade-CwZbp2Ca.js": asset257,
  "/assets/bicep-D2njIRU5.js": asset258,
  "/assets/html-derivative-DgyNW28a.js": asset259,
  "/assets/bsl-C4qeDxuX.js": asset260,
  "/assets/c-CyUOlKFr.js": asset261,
  "/assets/sql-CKXjX23X.js": asset262,
  "/assets/sdbl-C5Q1usnU.js": asset263,
  "/assets/cadence-bIHbUj02.js": asset264,
  "/assets/cairo-C_mOTUpN.js": asset265,
  "/assets/python-DgE28U1V.js": asset266,
  "/assets/clarity-A4x-rz24.js": asset267,
  "/assets/clojure-Bb2-3A0I.js": asset268,
  "/assets/cmake-Cv5ljclQ.js": asset269,
  "/assets/cobol-Cg3yRVOY.js": asset270,
  "/assets/codeowners-CKT8dJip.js": asset271,
  "/assets/coffee-CSg58a7P.js": asset272,
  "/assets/common-lisp-v102bg8X.js": asset273,
  "/assets/codeql-DXd8ggn3.js": asset274,
  "/assets/coq-CxCehFeR.js": asset275,
  "/assets/regexp-BW_zLBm-.js": asset276,
  "/assets/glsl-Bk7TyU8J.js": asset277,
  "/assets/crystal-kLfOnxTY.js": asset278,
  "/assets/shellscript-CE-5zpiL.js": asset279,
  "/assets/csv-AZNL9t8Q.js": asset280,
  "/assets/csharp-DFQpaWb6.js": asset281,
  "/assets/cue-nzsbQn5T.js": asset282,
  "/assets/cypher-BM7Pwunj.js": asset283,
  "/assets/d-TG9YRPoI.js": asset284,
  "/assets/dart-DArdxSyj.js": asset285,
  "/assets/desktop-Z9LhWKWr.js": asset286,
  "/assets/dax-B28Cho4e.js": asset287,
  "/assets/docker-DIG_IqVK.js": asset288,
  "/assets/dotenv-Bf0GLMGc.js": asset289,
  "/assets/diff-BlzBhZx2.js": asset290,
  "/assets/dream-maker-DBhfoDN-.js": asset291,
  "/assets/elixir-B1OcFvXE.js": asset292,
  "/assets/edge-C9mkmEUa.js": asset293,
  "/assets/emacs-lisp-fXIB3QbG.js": asset294,
  "/assets/elm-BX_9EnK8.js": asset295,
  "/assets/erb-CjsbKF3w.js": asset296,
  "/assets/ruby-CHyTNJrF.js": asset297,
  "/assets/haml-C-C08OMF.js": asset298,
  "/assets/lua-tkfysgZP.js": asset299,
  "/assets/yaml-B92AUxDB.js": asset300,
  "/assets/graphql-By4-2MiP.js": asset301,
  "/assets/jsx-BGEKFWBk.js": asset302,
  "/assets/erlang-Dh270pQQ.js": asset303,
  "/assets/markdown-CKXSK5AY.js": asset304,
  "/assets/fish-BiaFC76h.js": asset305,
  "/assets/fennel-CKW7gc4E.js": asset306,
  "/assets/fluent-C1VbA1FI.js": asset307,
  "/assets/fortran-fixed-form-VBUom2Po.js": asset308,
  "/assets/fortran-free-form-xZZnushS.js": asset309,
  "/assets/fsharp-B6CigNpP.js": asset310,
  "/assets/gdresource-B57lXvxj.js": asset311,
  "/assets/gdshader-MbeiIFWW.js": asset312,
  "/assets/gdscript-etqGfJNh.js": asset313,
  "/assets/genie-CTXGoN_z.js": asset314,
  "/assets/git-commit-BicZTByO.js": asset315,
  "/assets/git-rebase-Bzlpfr7M.js": asset316,
  "/assets/gherkin-DQeIZrj7.js": asset317,
  "/assets/glimmer-js-cZi37nA1.js": asset318,
  "/assets/gleam-B-IqXlZK.js": asset319,
  "/assets/gnuplot-BBjkHhdK.js": asset320,
  "/assets/glimmer-ts-BY3QTAW9.js": asset321,
  "/assets/go-BYCC9JQ2.js": asset322,
  "/assets/groovy-DjMbfbx0.js": asset323,
  "/assets/hack-Ce3HFLQu.js": asset324,
  "/assets/handlebars-BFxKmXBZ.js": asset325,
  "/assets/haxe-n0Q_eay_.js": asset326,
  "/assets/hcl-shhv74hy.js": asset327,
  "/assets/haskell-DtebQ3Kv.js": asset328,
  "/assets/hjson-BEMFYqr7.js": asset329,
  "/assets/hlsl-Pefxhtaj.js": asset330,
  "/assets/http-D0p2QOuJ.js": asset331,
  "/assets/hy-CTpXmg0M.js": asset332,
  "/assets/hurl-CeF7EoTQ.js": asset333,
  "/assets/imba-z_cUhu9e.js": asset334,
  "/assets/ini-DOGW4-0C.js": asset335,
  "/assets/hxml-B_SuSTPP.js": asset336,
  "/assets/jison-DRGa8fbr.js": asset337,
  "/assets/json5-DE06a0U2.js": asset338,
  "/assets/jsonc-BYi4HS05.js": asset339,
  "/assets/jsonl-CuhIcKDk.js": asset340,
  "/assets/jsonnet-DtQdHwK-.js": asset341,
  "/assets/jssm-BlhucWo7.js": asset342,
  "/assets/julia-Bh5qjrIj.js": asset343,
  "/assets/r-BfG_C0qz.js": asset344,
  "/assets/kotlin-DwKqsDKK.js": asset345,
  "/assets/kusto-w7PrLrBe.js": asset346,
  "/assets/latex-BuzO6rjU.js": asset347,
  "/assets/kdl-DJsF4U57.js": asset348,
  "/assets/tex-DZ7Smwga.js": asset349,
  "/assets/lean-Dle5D8N4.js": asset350,
  "/assets/less-C76OjOdF.js": asset351,
  "/assets/llvm-s1WuUfOe.js": asset352,
  "/assets/log-CbW7hOWU.js": asset353,
  "/assets/liquid-DdraCjph.js": asset354,
  "/assets/logo-BbooMuDm.js": asset355,
  "/assets/luau-CBwFb-vO.js": asset356,
  "/assets/make-s9FKP0VE.js": asset357,
  "/assets/marko-BsqRlKIY.js": asset358,
  "/assets/matlab-BQKM-LA_.js": asset359,
  "/assets/mdc-BBM-UqJy.js": asset360,
  "/assets/mdx-BWRhHdFl.js": asset361,
  "/assets/mermaid-DrapLM8U.js": asset362,
  "/assets/mipsasm-BElnB_7Q.js": asset363,
  "/assets/mojo-Dz6zCmiK.js": asset364,
  "/assets/move-Dvu4btzz.js": asset365,
  "/assets/narrat-Cy2k80UN.js": asset366,
  "/assets/nextflow-BO4ujnzu.js": asset367,
  "/assets/nim-Cm6-Nayq.js": asset368,
  "/assets/objective-c-sgtl-PdD.js": asset369,
  "/assets/nushell-Dqv-0Q5X.js": asset370,
  "/assets/nginx-XmDIhN78.js": asset371,
  "/assets/objective-cpp-BTQ37cYs.js": asset372,
  "/assets/ocaml-BvBP9Lm0.js": asset373,
  "/assets/openscad-Dmi2c_42.js": asset374,
  "/assets/pascal-DYjw0AuS.js": asset375,
  "/assets/perl-Djxv1YJ9.js": asset376,
  "/assets/php-DEfiO3Bd.js": asset377,
  "/assets/pkl-Cij4Vm9z.js": asset378,
  "/assets/plsql-Bd6NdBJI.js": asset379,
  "/assets/po-CUhVi7la.js": asset380,
  "/assets/polar-B-qJ3AIy.js": asset381,
  "/assets/powerquery-CC1XieQO.js": asset382,
  "/assets/powershell-DdRAnR4Z.js": asset383,
  "/assets/prolog-bSi0SE3D.js": asset384,
  "/assets/prisma-C0hJlfqX.js": asset385,
  "/assets/proto-DIGPV07t.js": asset386,
  "/assets/pug-ClQUpJlV.js": asset387,
  "/assets/purescript-CxgsQa43.js": asset388,
  "/assets/puppet-ja2MI9-b.js": asset389,
  "/assets/qml-BEkX6VoX.js": asset390,
  "/assets/qmldir-DNYHzgow.js": asset391,
  "/assets/qss-BZsEMKxJ.js": asset392,
  "/assets/racket-CzHBKLyy.js": asset393,
  "/assets/razor-8rj0VRTp.js": asset394,
  "/assets/raku-CPccoUN1.js": asset395,
  "/assets/reg-DkqHJyC0.js": asset396,
  "/assets/rel-BIqKdwke.js": asset397,
  "/assets/rst-8IYWyo0X.js": asset398,
  "/assets/rosmsg-TcL_zzr8.js": asset399,
  "/assets/riscv-s6spwTFp.js": asset400,
  "/assets/rust-DJErdhjk.js": asset401,
  "/assets/sas-BZeeyq_z.js": asset402,
  "/assets/sass-CIfQ9yqV.js": asset403,
  "/assets/scala-CWwlNtab.js": asset404,
  "/assets/scheme-ByM66cy_.js": asset405,
  "/assets/shaderlab-DNkMdb2B.js": asset406,
  "/assets/shellsession-BhddCRKA.js": asset407,
  "/assets/smalltalk-GKfhTxrk.js": asset408,
  "/assets/solidity-DanOLEvk.js": asset409,
  "/assets/soy-C6ERzLIv.js": asset410,
  "/assets/sparql-CHK3vDkL.js": asset411,
  "/assets/turtle-whXsfw69.js": asset412,
  "/assets/splunk-YU1HCmJX.js": asset413,
  "/assets/stata-BJqnY-gO.js": asset414,
  "/assets/svelte-DmnhoTkn.js": asset415,
  "/assets/stylus-CHekGIgu.js": asset416,
  "/assets/ssh-config-Cpnw3KEt.js": asset417,
  "/assets/swift-Deru3G9w.js": asset418,
  "/assets/system-verilog-rKNYENrf.js": asset419,
  "/assets/systemd-C1FfcI00.js": asset420,
  "/assets/talonscript-bksoRmW6.js": asset421,
  "/assets/tasl-Bl4tsGRM.js": asset422,
  "/assets/templ-CyHhV9jl.js": asset423,
  "/assets/terraform-Ba94thAr.js": asset424,
  "/assets/toml-Btlk-g9G.js": asset425,
  "/assets/tsv-DYfmKMIW.js": asset426,
  "/assets/twig-vsFUeHgy.js": asset427,
  "/assets/typespec-C_z-8Pri.js": asset428,
  "/assets/tcl-B2_VAYrd.js": asset429,
  "/assets/typst-D2RORpaG.js": asset430,
  "/assets/v-CvM42WIw.js": asset431,
  "/assets/vala-B_5xOBNr.js": asset432,
  "/assets/vb-BVDm3zBt.js": asset433,
  "/assets/verilog-D5iownw6.js": asset434,
  "/assets/vhdl-Bmgbkl_-.js": asset435,
  "/assets/viml-3ZODU9FQ.js": asset436,
  "/assets/vue-html-CRAum25o.js": asset437,
  "/assets/vue-vine-CDS6dxm6.js": asset438,
  "/assets/vyper-B6NKdirK.js": asset439,
  "/assets/wasm-LUzQYg3H.js": asset440,
  "/assets/wenyan-8fXatRyt.js": asset441,
  "/assets/wgsl-CECC3vJ5.js": asset442,
  "/assets/wit-MEd50GYB.js": asset443,
  "/assets/wolfram-CmMaIVaG.js": asset444,
  "/assets/wikitext-BaRWL9sq.js": asset445,
  "/assets/xsl-Btrj9DhN.js": asset446,
  "/assets/zig-LhWa2ADv.js": asset447,
  "/assets/andromeeda-C-Jbm3Hp.js": asset448,
  "/assets/catppuccin-frappe-DFWUc33u.js": asset449,
  "/assets/ayu-dark-Cv9koXgw.js": asset450,
  "/assets/zenscript-Dja4fBOE.js": asset451,
  "/assets/catppuccin-latte-C9dUb6Cb.js": asset452,
  "/assets/catppuccin-macchiato-DQyhUUbL.js": asset453,
  "/assets/catppuccin-mocha-D87Tk5Gz.js": asset454,
  "/assets/dark-plus-C3mMm8J8.js": asset455,
  "/assets/aurora-x-D-2ljcwZ.js": asset456,
  "/assets/dracula-soft-BXkSAIEj.js": asset457,
  "/assets/everforest-dark-BgDCqdQA.js": asset458,
  "/assets/dracula-BzJJZx-M.js": asset459,
  "/assets/everforest-light-C8M2exoo.js": asset460,
  "/assets/github-dark-DHJKELXO.js": asset461,
  "/assets/github-dark-dimmed-DH5Ifo-i.js": asset462,
  "/assets/github-dark-high-contrast-E3gJ1_iC.js": asset463,
  "/assets/github-light-DAi9KRSo.js": asset464,
  "/assets/github-dark-default-Cuk6v7N8.js": asset465,
  "/assets/github-light-default-D7oLnXFd.js": asset466,
  "/assets/github-light-high-contrast-BfjtVDDH.js": asset467,
  "/assets/gruvbox-dark-hard-CFHQjOhq.js": asset468,
  "/assets/gruvbox-dark-medium-GsRaNv29.js": asset469,
  "/assets/gruvbox-dark-soft-CVdnzihN.js": asset470,
  "/assets/gruvbox-light-hard-CH1njM8p.js": asset471,
  "/assets/gruvbox-light-medium-DRw_LuNl.js": asset472,
  "/assets/gruvbox-light-soft-hJgmCMqR.js": asset473,
  "/assets/houston-DnULxvSX.js": asset474,
  "/assets/kanagawa-dragon-CkXjmgJE.js": asset475,
  "/assets/kanagawa-wave-DWedfzmr.js": asset476,
  "/assets/kanagawa-lotus-CfQXZHmo.js": asset477,
  "/assets/laserwave-DUszq2jm.js": asset478,
  "/assets/light-plus-B7mTdjB0.js": asset479,
  "/assets/material-theme-D5KoaKCx.js": asset480,
  "/assets/material-theme-lighter-B0m2ddpp.js": asset481,
  "/assets/material-theme-palenight-Csfq5Kiy.js": asset482,
  "/assets/material-theme-ocean-CyktbL80.js": asset483,
  "/assets/material-theme-darker-BfHTSMKl.js": asset484,
  "/assets/min-dark-CafNBF8u.js": asset485,
  "/assets/min-light-CTRr51gU.js": asset486,
  "/assets/monokai-D4h5O-jR.js": asset487,
  "/assets/night-owl-C39BiMTA.js": asset488,
  "/assets/nord-Ddv68eIx.js": asset489,
  "/assets/one-dark-pro-DVMEJ2y_.js": asset490,
  "/assets/plastic-3e1v2bzS.js": asset491,
  "/assets/one-light-PoHY5YXO.js": asset492,
  "/assets/poimandres-CS3Unz2-.js": asset493,
  "/assets/rose-pine-qdsjHGoJ.js": asset494,
  "/assets/rose-pine-dawn-DHQR4-dF.js": asset495,
  "/assets/red-bN70gL4F.js": asset496,
  "/assets/rose-pine-moon-D4_iv3hh.js": asset497,
  "/assets/slack-dark-BthQWCQV.js": asset498,
  "/assets/slack-ochin-DqwNpetd.js": asset499,
  "/assets/snazzy-light-Bw305WKR.js": asset500,
  "/assets/solarized-dark-DXbdFlpD.js": asset501,
  "/assets/synthwave-84-CbfX1IO0.js": asset502,
  "/assets/solarized-light-L9t79GZl.js": asset503,
  "/assets/tokyo-night-hegEt444.js": asset504,
  "/assets/vitesse-black-Bkuqu6BP.js": asset505,
  "/assets/vitesse-dark-D0r3Knsf.js": asset506,
  "/assets/vitesse-light-CVO1_9PV.js": asset507,
  "/assets/cpp-CofmeUqb.js": asset508,
  "/assets/jinja-4LBKfQ-Z.js": asset509,
  "/assets/vesper-DU1UobuO.js": asset510,
  "/assets/nix-c8nO5XWb.js": asset511,
  "/assets/cpp-C28rag7_.js": asset512,
  "/assets/jinja-DlBE7Xgz.js": asset513,
  "/assets/nix-DcZRBjkC.js": asset514,
  "/assets/angular-ts-BwZT4LLn.js": asset515,
  "/assets/angular-ts-BfBSdvnY.js": asset516,
  "/assets/vue-DnHKYNfI.js": asset517,
  "/assets/angular-html-CU67Zn6k.js": asset518,
  "/assets/angular-html-6NEUuZou.js": asset519,
  "/assets/vue-BJuclMoA.js": asset520,
  "/assets/ts-tags-zn1MmPIZ.js": asset521,
  "/assets/index-DvAfiR5P.js": asset522,
  "/assets/worker-NULm4lOi.js": asset523,
  "/assets/ts-tags-DMPjx__B.js": asset524,
};
